const String AboutInfo =
    "With May Week cancelled this year due to Coronavirus, we wanted to turn this into something positive and give back to "
    "society to help tackle Covid-19. That's why we launched the Big May Ball Appeal - Coronavirus (The Big MAC), to raise "
    "money from your ticket refunds. We like to call this idea \'refundraising\'. We hope that May Ball ticket holders "
    "consider donating a portion of their refund and that those without refunds also consider donating via our percent link."
    "\nThe appeal will last until the end of May Week (19 June)."
    "\n\n\n"
    "Our survey taken by 200 Cambridge students highlighted that most wanted a Covid-related, co-benefit and local charity, "
    "which is why we decided to raise money for The Cambridge Centre for the Study of Existential Risk (CSER) and Addenbrooke's "
    "Charitable Trust."
    "\nCSER is a research centre at the University of Cambridge, intended to study possible extinction-level threats, "
    "including pandemics; and has a track record for engaging with policy makers."
    "\nAddenbrooke's, an intitution closely linked to Cambridge University, is raising money to support their staff during this "
    "difficult time and provide equipment needed to support the Intensive Care Unit. Most importantly, all money raised for "
    "Addenbrooke's will go towards providing support for staff that goes above and beyond what NHS funding would provide."
    "\n\n\n"
    "Ticket holders will be contacted by their May Ball Committees on how to donate and anyone else is encouraged to donate via "
    "the percent link. Why not donate the cost of your Cindies' tickets, haircut, formal meal or weekly college rent?"
    "\n\n\n"
    "With the Coronavirus pandemic taking away our beloved May Week, let's turn this into something positive and come together "
    "as a university to raise as much as we can to tackle Coronavirus, so next year we can party again in a safer world!"
    "\n\n\n"
    "With thanks to The University of Cambridge, The May Ball Predidents' Committee and Cambridge RAG for all their support in making "
    "this appeal happen."
    "\n\n\n"
    "The Big MAC. Give back when you get back.";